[package]
name = "utokyo-FSC-IS4029L1-assignment-m1"
version = "0.0.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
eyre = "0.6.12"
futures = "0.3.31"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
winit = "0.30.9"
wgpu = "25.0.0"
