combine_control_expr = false
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "One"
hex_literal_case = "Upper"
imports_granularity = "One"
imports_layout = "Vertical"
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
single_line_if_else_max_width = 0
struct_lit_single_line = false
use_field_init_shorthand = true
use_try_shorthand = true
